---
inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - 'spec/lib/browse_everything/driver/file_system_spec.rb'

Style/GuardClause:
  Exclude:
    - 'lib/browse_everything/driver/file_system.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/lib/browse_everything/driver/file_system_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/lib/browse_everything/upload/file_system/resource_spec.rb'
